// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Usando as credenciais do projeto Supabase diretamente para garantir a conexão
const SUPABASE_URL = "https://inqidhstfzmjeodtszbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlucWlkaHN0ZnptamVvZHRzemJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDQ1MTcsImV4cCI6MjA3MzAyMDUxN30.UgKpeUcLe5RP16tKZC85g_WppOiUzsLHuapNE32YAjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});